name: connect-publish
on:
  push:
    branches: [main]

jobs:
  connect-publish:
    name: connect-publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://colorado.posit.co/rsc/connect/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          dir: |
            .:connect_cicd_test